language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  # - "2.7"
  - "3.6"
env:
  # - NUMPY_VERSION="1.11.3"
  - NUMPY_VERSION=""
install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  # test against older version of numpy too
  # - conda install scipy scikit-learn joblib
  - conda install matplotlib
  - if [[ "$NUMPY_VERSION" == "" ]]; then
      pip install numpy;
    else
      pip install numpy==$NUMPY_VERSION;
    fi
  # - pip install mne pytest codecov mock coverage
  - pip install -e '.[test]'
  - pip install codecov coverage

script:
  - coverage run -m pytest

after_success:
  - codecov
